name: Build and Release PDFs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Dependencies
        run: |
          cp latex-common/*.cls moma_seminar/
          cp latex-common/*.cls moma_analysis_report/

      - name: Compile MoMa Seminar
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: moma_seminar
          post_compile: |
            latexmk -c
            rm -f *.cls
          latexmk_shell_escape: true

      - name: Compile Critical Analysis Report
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: moma_analysis_report
          post_compile: |
            latexmk -c
            rm -f *.cls
          latexmk_shell_escape: true

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: research-papers
          path: |
            moma_seminar/dist/main.pdf
            moma_analysis_report/dist/main.pdf
